
const STATE_PLAYING =  'STATE_PLAYING'
const STATE_PAUSED = 'STATE_PAUSED'
const STATE_ERROR =  'STATE_ERROR'
const STATE_STOPPED =  'STATE_STOPPED'

export default {
  STATE_PLAYING,
  STATE_PAUSED,
  STATE_ERROR,
  STATE_STOPPED,
}
